version: "3.9"
   
services:
  frontend:
    image: imagetextdetectionapp:frontend-latest
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    networks: 
      - itd_net
    depends_on:
      - backend

  backend:
    image: imagetextdetectionapp:backend-latest
    env_file:
      - server-environment.env
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
    networks: 
      - itd_net

networks:
  itd_net: