version: "3.9"
   
services:
  backend:
    build: ./server/.  
    environment:
      - APP_ENV=DOCKER-DEV
      - FLASK_APP=app.py
    ports:
      - "5000:5000"  
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0"]    
  frontend:
    build: ./client/.
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./volume:/server
    ports:
      - "80:80"
    depends_on:
      - backend